version: "3.1"
services:
  redis:
      image: redis:alpine
      container_name: myapp-redis
      command: redis-server --appendonly yes --requirepass "myapp"
      volumes:
      - ./data/redis:/data
      ports:
        - "8002:6379"